In [56]:
import pandas as pd

In [57]:
# loading the product and translation product datasets
products = pd.read_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\raw_data\products.csv")
translation_prod = pd.read_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\raw_data\product_translation.csv")

In [58]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [59]:
translation_prod.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [60]:
# Checking structure, summary, and missing values in products
print(products.shape)
print(products.info())
print(products.describe())
print(products.isnull().sum())

(32951, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None
       product_name_lenght  product_description_lenght  product_photos_qty  \
count         32341.000000                32341.000000        32341.000000
mean             48.476949                  771.495285            2.188986
std              10.245741                  635.115225            1.736766
min               5.000000                    4.000000            1.000000
25%              42.000000                  339.000000            1.000000
50%              51.000000                  595.000000            1.000000
75%              57.000000                  972.000000            3.000000
max              76.000000                 3992.000000           20.000000

       product_weight_g  product_length_cm  product_height_cm  \
count      32949.000000       32949.000000       32949.000000
mean        2276.472488          30.815078          16.937661
std         4282.038731          16.914458          13.637554
min            0.000000           7.000000           2.000000
25%          300.000000          18.000000           8.000000
50%          700.000000          25.000000          13.000000
75%         1900.000000          38.000000          21.000000
max        40425.000000         105.000000         105.000000

       product_width_cm
count      32949.000000
mean          23.196728
std           12.079047
min            6.000000
25%           15.000000
50%           20.000000
75%           30.000000
max          118.000000
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [61]:
# Checking structure, summary, and missing values in translation table
print(translation_prod.shape)
print(translation_prod.info())
print(translation_prod.describe())
print(translation_prod.isnull().sum())

(71, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1
product_category_name            0
product_category_name_english    0
dtype: int64

In [62]:
# merging product with translation prod table for english translation of product categories

products_merged = pd.merge(products, translation_prod, on = 'product_category_name', how = 'left')
products_merged.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [63]:
# renaming the column name and dropping the name column which was in different language after merging
products_merged = products_merged.rename(
    columns = {'product_category_name_english' : 'product_category'})

products_merged.drop(columns = ['product_category_name'], inplace = True)

products_merged.head()

,product_id,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [64]:
# keeping only needed columns for analysis
products = products_merged[
["product_id", "product_category"]]
products.head()

                         product_id product_category
0  1e9e8ef04dbcff4541ed26657ea517e5        perfumery
1  3aa071139cb16b67ca9e5dea641aaa2f              art
2  96bd76ec8810374ed1b65e291975717f   sports_leisure
3  cef67bcfe19066a932b7673e239eb23d             baby
4  9dc1a7de274444849c219cff195d0b71       housewares

In [65]:
# filling the missing product categories with 'unknown'
products.loc[:,'product_category'] = products['product_category'].fillna('Unknown')

In [66]:
# checking for any null values after cleaning
print(products.isnull().sum())
print(products.head(10))

product_id          0
product_category    0
dtype: int64
                         product_id     product_category
0  1e9e8ef04dbcff4541ed26657ea517e5            perfumery
1  3aa071139cb16b67ca9e5dea641aaa2f                  art
2  96bd76ec8810374ed1b65e291975717f       sports_leisure
3  cef67bcfe19066a932b7673e239eb23d                 baby
4  9dc1a7de274444849c219cff195d0b71           housewares
5  41d3672d4792049fa1779bb35283ed13  musical_instruments
6  732bd381ad09e530fe0a5f457d81becb           cool_stuff
7  2548af3e6e77a690cf3eb6368e9ab61e      furniture_decor
8  37cc742be07708b53a98702e77a21a02      home_appliances
9  8c92109888e8cdf9d66dc7e463025574                 toys

In [67]:
# checking for any duplicate raws
products['product_id'].duplicated().sum()

np.int64(0)

In [68]:
# removing any extra spaces and standardizing text
products.loc[:, 'product_category'] = products['product_category'].str.strip().str.lower()

In [69]:
# saving the file
products_cleaned = products.to_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\products_cleaned.csv", index=False)

In [70]:
# loading order item dataset
order_items = pd.read_csv(r'C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\raw_data\order_items.csv')
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [71]:
# Checking structure, summary, and missing values in order items
print(order_items.shape)
print(order_items.info())
print(order_items.describe())
print(order_items.isnull().sum())

(112650, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None
       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [72]:
# checking for duplicates
order_items.duplicated().sum()

np.int64(0)

In [73]:
# changing the shipping dae to datetime format
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

In [74]:
# creating shipping ratio column for analysis
order_items['shipping_ratio'] = order_items['freight_value']/order_items['price']

In [75]:
# summary for shipping ratio
print(order_items['shipping_ratio'].describe())
order_items.head()

count    112650.000000
mean          0.320864
std           0.349894
min           0.000000
25%           0.134034
50%           0.231356
75%           0.393036
max          26.235294
Name: shipping_ratio, dtype: float64

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_ratio
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,0.225637
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,0.083076
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,0.089799
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,0.984604
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,0.090745

In [76]:
# finding order items where shipping ratio is high
order_items[order_items['shipping_ratio']>1].shape

(4124, 8)

In [109]:
# (4124/112650)*100 = 3.6(approx) Approximately 3.6% of orders have shipping costs exceeding product price

In [78]:
# creating column for high shipping order items
order_items['high_shipping'] = order_items['shipping_ratio'] > 1

In [79]:
order_items['high_shipping'].value_counts()

high_shipping
False    108526
True       4124
Name: count, dtype: int64

In [80]:
order_items.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_ratio,high_shipping
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,0.225637,False
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,0.083076,False
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,0.089799,False
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,0.984604,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,0.090745,False
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69,0.579452,False
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85,0.595477,False
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75,0.087346,False
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65,0.079822,False
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40,0.211150,False

In [81]:
# saving the cleaned file
order_items_cleaned = order_items.to_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\order_items_cleaned.csv", index = False)

In [82]:
# merging the product and order items dataset
order_products = order_items.merge(products, on = 'product_id', how = 'left')

In [83]:
order_products.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_ratio,high_shipping,product_category
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,0.225637,False,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,0.083076,False,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,0.089799,False,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,0.984604,False,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,0.090745,False,garden_tools

In [84]:
# Checking structure, summary, and missing values in merged file
print(order_products.shape)
print(order_products.info())
print(order_products.describe())
print(order_products.isnull().sum())

(112650, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   shipping_ratio       112650 non-null  float64
 8   high_shipping        112650 non-null  bool
 9   product_category     112650 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 7.8+ MB
None
       order_item_id            shipping_limit_date          price  \
count  112650.000000                         112650  112650.000000
mean        1.197834  2018-01-07 15:36:52.192685312     120.653739
min         1.000000            2016-09-19 00:15:34       0.850000
25%         1.000000     2017-09-20 20:57:27.500000      39.900000
50%         1.000000            2018-01-26 13:59:35      74.990000
75%         1.000000  2018-05-10 14:34:00.750000128     134.900000
max        21.000000            2020-04-09 22:35:08    6735.000000
std         0.705124                            NaN     183.633928

       freight_value  shipping_ratio
count  112650.000000   112650.000000
mean       19.990320        0.320864
min         0.000000        0.000000
25%        13.080000        0.134034
50%        16.260000        0.231356
75%        21.150000        0.393036
max       409.680000       26.235294
std        15.806405        0.349894
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
shipping_ratio         0
high_shipping          0
product_category       0
dtype: int64

In [85]:
# saving the merged file
order_products_cleaned = order_products.to_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\order_products_cleaned.csv", index = False)

In [86]:
# loading the orders dataset
orders = pd.read_csv(r'C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\raw_data\orders.csv')

In [87]:
# Checking structure, summary, and missing values in orders
print(orders.shape)
print(orders.info())
print(orders.describe())
print(orders.isnull().sum())
print(orders.duplicated().sum())

(99441, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-08-02 12:05:26  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-08 19:36:48
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
0

In [88]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [89]:
# changing the columns type to datetime format
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [90]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [91]:
# creating delivery days columns
orders['delivery_days'] = (orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']).dt.days

In [92]:
# creating column for late deliveries
orders['delivery_delay'] = (orders['order_delivered_customer_date'] - orders['order_estimated_delivery_date']).dt.days

In [93]:
# creating true false column for analysis
orders['is_delivery_late'] = orders['delivery_delay']>0

In [94]:
# checking for uniques values
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [95]:
# Checking summary
print(orders['delivery_days'].describe())
print(orders['delivery_days'].describe())

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64
count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

In [96]:
# saving the file
orders_cleaned = orders.to_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\orders_cleaned.csv", index = False)

In [97]:
# loading files
orders = pd.read_csv(r'C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\orders_cleaned.csv')
order_products = pd.read_csv(r'C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\order_products_cleaned.csv')

In [98]:
print(orders.shape)
print(order_products.shape)

(99441, 11)
(112650, 10)

In [99]:
# merging and creating the final dataset ready for analysis
orders_products_final = pd.merge(order_products, orders, on = 'order_id', how = 'left')

In [100]:
orders_products_final.shape

(112650, 20)

In [101]:
orders_products_final.head(15)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,shipping_ratio,high_shipping,product_category,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_days,delivery_delay,is_delivery_late
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,0.225637,False,cool_stuff,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,7.0,-9.0,False
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,0.083076,False,pet_shop,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,16.0,-3.0,False
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,0.089799,False,furniture_decor,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,7.0,-14.0,False
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,0.984604,False,perfumery,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,6.0,-6.0,False
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,0.090745,False,garden_tools,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,25.0,-16.0,False
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69,0.579452,False,housewares,816cbea969fe5b689b39cfc97a506742,delivered,2017-05-15 21:42:34,2017-05-17 03:55:27,2017-05-17 11:05:55,2017-05-22 13:44:35,2017-06-06,6.0,-15.0,False
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85,0.595477,False,telephony,32e2e6ab09e778d99bf2e0ecd4898718,delivered,2017-12-10 11:53:48,2017-12-10 12:10:31,2017-12-12 01:07:48,2017-12-18 22:03:38,2018-01-04,8.0,-17.0,False
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75,0.087346,False,garden_tools,9ed5e522dd9dd85b4af4a077526d8117,delivered,2018-07-04 12:08:27,2018-07-05 16:35:48,2018-07-05 12:15:00,2018-07-09 14:04:07,2018-07-25,5.0,-16.0,False
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65,0.079822,False,health_beauty,16150771dfd4776261284213b89c304e,delivered,2018-03-19 18:40:33,2018-03-20 18:35:21,2018-03-28 00:37:42,2018-03-29 18:17:31,2018-03-29,9.0,0.0,False
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40,0.211150,False,books_technical,351d3cb2cee3c7fd0af6616c82df21d3,delivered,2018-07-02 13:59:39,2018-07-02 14:10:56,2018-07-03 14:25:00,2018-07-04 17:28:31,2018-07-23,2.0,-19.0,False
10,00061f2a7bc09da83e415a52dc8a4af1,1,d63c1011f49d98b976c352955b1c4bea,cc419e0650a3c5ba77189a1882b7556a,2018-03-29 22:28:09,59.99,8.88,0.148025,False,health_beauty,c6fc061d86fab1e2b2eac259bac71a49,delivered,2018-03-24 22:16:10,2018-03-24 22:28:09,2018-03-27 05:26:55,2018-03-29 00:04:19,2018-04-09,4.0,-11.0,False
11,00063b381e2406b52ad429470734ebd5,1,f177554ea93259a5b282f24e33f65ab6,8602a61d680a10a82cceeeda0d99ea3d,2018-07-31 17:30:39,45.00,12.98,0.288444,False,fashion_bags_accessories,6a899e55865de6549a58d2c6845e5604,delivered,2018-07-27 17:21:27,2018-07-27 18:00:06,2018-07-30 14:52:00,2018-08-07 13:56:52,2018-08-07,10.0,0.0,False
12,0006ec9db01a64e59a68b2c340bf65a7,1,99a4788cb24856965c36a24e339b6058,4a3ca9315b744ce9f8e9374361493884,2018-07-26 17:24:20,74.00,23.32,0.315135,False,bed_bath_table,5d178120c29c61748ea95bac23cb8f25,delivered,2018-07-24 17:04:17,2018-07-24 17:24:20,2018-07-25 11:02:00,2018-07-31 01:04:15,2018-08-22,6.0,-22.0,False
13,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37,0.267936,False,garden_tools,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:21,2018-02-15 03:55:52,2018-02-20 18:23:28,2018-02-26 13:55:22,2018-03-06,12.0,-8.0,False
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.90,13.37,0.267936,False,garden_tools,2355af7c75e7c98b43a87b2a7f210dc5,delivered,2018-02-13 22:10:21,2018-02-15 03:55:52,2018-02-20 18:23:28,2018-02-26 13:55:22,2018-03-06,12.0,-8.0,False

In [102]:
# Checking structure, summary, and missing values in final dataset
print(orders_products_final.shape)
print(orders_products_final.info())
print(orders_products_final.describe())
print(orders_products_final.isnull().sum())
print(orders_products_final.duplicated().sum())

(112650, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       112650 non-null  object
 1   order_item_id                  112650 non-null  int64
 2   product_id                     112650 non-null  object
 3   seller_id                      112650 non-null  object
 4   shipping_limit_date            112650 non-null  object
 5   price                          112650 non-null  float64
 6   freight_value                  112650 non-null  float64
 7   shipping_ratio                 112650 non-null  float64
 8   high_shipping                  112650 non-null  bool
 9   product_category               112650 non-null  object
 10  customer_id                    112650 non-null  object
 11  order_status                   112650 non-null  object
 12  order_purchase_timestamp       112650 non-null  object
 13  order_approved_at              112635 non-null  object
 14  order_delivered_carrier_date   111456 non-null  object
 15  order_delivered_customer_date  110196 non-null  object
 16  order_estimated_delivery_date  112650 non-null  object
 17  delivery_days                  110196 non-null  float64
 18  delivery_delay                 110196 non-null  float64
 19  is_delivery_late               112650 non-null  bool
dtypes: bool(2), float64(5), int64(1), object(12)
memory usage: 15.7+ MB
None
       order_item_id          price  freight_value  shipping_ratio  \
count  112650.000000  112650.000000  112650.000000   112650.000000
mean        1.197834     120.653739      19.990320        0.320864
std         0.705124     183.633928      15.806405        0.349894
min         1.000000       0.850000       0.000000        0.000000
25%         1.000000      39.900000      13.080000        0.134034
50%         1.000000      74.990000      16.260000        0.231356
75%         1.000000     134.900000      21.150000        0.393036
max        21.000000    6735.000000     409.680000       26.235294

       delivery_days  delivery_delay
count  110196.000000   110196.000000
mean       12.007723      -12.030201
std         9.451455       10.160157
min         0.000000     -147.000000
25%         6.000000      -17.000000
50%        10.000000      -13.000000
75%        15.000000       -7.000000
max       209.000000      188.000000
order_id                            0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
shipping_ratio                      0
high_shipping                       0
product_category                    0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
delivery_days                    2454
delivery_delay                   2454
is_delivery_late                    0
dtype: int64
0

In [103]:
orders_products_final = orders_products_final.to_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\orders_products_final.csv", index = False)

In [104]:
orders_products_final = pd.read_csv(r"C:\Users\Amarjeet\Downloads\Revenue_Leagkage_Analysis\Cleaned_data\orders_products_final.csv")

In [105]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\amarjeet\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\amarjeet\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\amarjeet\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\amarjeet\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [106]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:@localhost/revenue_leakage")

In [107]:
orders_products_final.to_sql(
    "orders_products_final",
    engine,
    if_exists="replace",
    index=False
)

112650

In [108]:
# What percentage of orders have high shipping cost?
# Which product categories have the highest shipping ratio?
# How many orders are delivered late?
# Which categories have the most late deliveries?
# Which categories lose the most revenue to shipping?